In [1]:
#Small Prime Method
import numpy as np

A=np.array([[4,5],[6,-7]])
print(A)

#det A <= n^(n/2)*B^(n)

(r,w)=np.shape(A)
n=r
print("Dimention of the matrix A is ",n,"x",n)

B=np.absolute(A).max()

h=n**(n/2)*B**(n)
print("Hadamard bound is of A is ",h)

H=h*2

P=[]
p0=1
for p in range(1,1000):
  if(p>1 and p0<=H):
    for i in range(2,p):
      if(p%i==0):
        break
    else:
      P.append(p)
      p0=p0*p
print("Modulo classes of A is",P)

DET=[]
N=1
for i in range(0,len(P)):
  Q=np.empty((n,n))
  for j in range(0,n):
    for k in range(0,n):
      for q in range(0,P[i]):
        if((A[j,k]-q)%P[i]==0):
          Q[j,k]=q
  print(Q)
  D=np.linalg.det(Q)
  DET.append(round(D))
  N=N*P[i]
print("Determinants of modulo class matrices",DET)
print("N =",N)

a=[]
ns=[]
for i in range(0,len(P)):
  if(abs(DET[i])>abs(P[i])):
    for j in range(0,P[i]):
      if((DET[i]-j)%P[i]==0):
        a.append(j)
  else:
    a.append(DET[i])
  ns.append(N/P[i])
print("a's =",a)
print("n's =",ns)

b=[]
for i in range(0,len(P)):
  for j in range(0,P[i]):
    if((j*ns[i]-1)%P[i]==0):
      b.append(j)
print("b's =",b)

expr=0
for i in range(0,len(P)):
  expr=expr+a[i]*b[i]*ns[i]
print("SUM of a(i)*b(i)*n(i) =",expr)

for i in range(0,int(N)):
  if((expr-i)%N==0):
    x=i
print(x)
  
S=[];
for d in range(-int(x),int(x)):
  if((d-x)%N==0):
    S.append(d)
print("Solutions are",S)

for i in range(0,len(S)):
  if(abs(S[i])==np.absolute(S).min()):
    print("Determinant of A is",S[i])


[[ 4  5]
 [ 6 -7]]
Dimention of the matrix A is  2 x 2
Hadamard bound is of A is  98.0
Modulo classes of A is [2, 3, 5, 7]
[[0. 1.]
 [0. 1.]]
[[1. 2.]
 [0. 2.]]
[[4. 0.]
 [1. 3.]]
[[4. 5.]
 [6. 0.]]
Determinants of modulo class matrices [0, 2, 12, -30]
N = 210
a's = [0, 2, 2, 5]
n's = [105.0, 70.0, 42.0, 30.0]
b's = [1, 1, 3, 4]
SUM of a(i)*b(i)*n(i) = 992.0
152
Solutions are [-58]
Determinant of A is -58
